import { Image } from './image.interface';

export const IMAGES: Image[] = [
  {
    id: 1,
    title: 'Balloons',
    category: 'Travel',
    description: 'blablabla',
    date: 'March 03, 2026',
    imageUrl: 'travel_1.jpg',
  },
  {
    id: 2,
    title: 'Coast Town',
    category: 'Travel',
    description: 'blablabla',
    date: 'April 7, 2023',
    imageUrl: 'travel_2.jpg',
  },
  {
    id: 3,
    title: 'Boats on Lake',
    category: 'Travel',
    description: 'blablabla',
    date: 'April 20, 2017',
    imageUrl: 'travel_3.jpg',
  },
  {
    id: 4,
    title: 'Couple on Meadow',
    category: 'Wedding',
    description: 'blablabla',
    date: 'March 03, 2026',
    imageUrl: 'wedding_1.jpg',
  },
  {
    id: 5,
    title: 'Flowers',
    category: 'Wedding',
    description: 'blablabla',
    date: 'June 24, 2024',
    imageUrl: 'wedding_2.jpg',
  },
  {
    id: 6,
    title: 'Holding Hands',
    category: 'Wedding',
    description: 'blablabla',
    date: 'August 01, 2020',
    imageUrl: 'wedding_3.jpg',
  },
  {
    id: 7,
    title: 'Portrait 1',
    category: 'Portrait',
    description: 'blablabla',
    date: 'November 03, 2013',
    imageUrl: 'portrait_1.jpg',
  },
  {
    id: 8,
    title: 'Portrait 2',
    category: 'Portrait',
    description: 'blablabla',
    date: 'December 12, 2018',
    imageUrl: 'portrait_2.jpg',
  },
  {
    id: 9,
    title: 'Portrait 3',
    category: 'Portrait',
    description: 'blablabla',
    date: 'February 03, 2013',
    imageUrl: 'portrait_3.jpg',
  },
];
